### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sargreal** [Fekide/strapi-plugin-deepl#1]
- [x] Ignore fields that are not translated
- [x] Ignore dates, enumeration, email, json
- [x] Allow translation of nested data
  - [x] components
  - [x] dynamic zones
- [ ] Configuration of free Api and token also through admin
- [ ] Overview of api usage in admin panel -> api done
- [ ] batch translation (needs to also 'translate' uids)
  - [ ] include overview of translation status to start translating
- [x] translate relations as well
- [ ] Advanced Markdown and HTML translation (DeepL supports xml tag filtering, so HTML should work well and Markdown could be parsed to HTML and back -> Configuration of the behaviour required)
- [ ] Tests
  - [x] unit
  - [ ] e2e

**Comment by thochi** [comment]
@sargreal nice work! very useful plugin.

Are there any plans to ignore 'translate' for locals which can not be handled by the provider but are anyway in use for 'copy'? right now i run into errors for locals which are not supported in deepl, but used in my app.
